lang: fr

teleport:
  cooldown_seconds: 5
  request_expire_seconds: 60

messages:
  fr:
    only_players: "&cCette commande est réservée aux joueurs."
    craft_opened: "&aÉtabli ouvert."
    craft_no_permission: "&cVous n'avez pas la permission d'utiliser /craft."
    ec_opened: "&aEnderChest ouvert."
    ec_no_permission: "&cVous n'avez pas la permission d'utiliser /ec."
    furnace_done: "&aVos objets ont été fondus."
    furnace_no_permission: "&cVous n'avez pas la permission d'utiliser /furnace."
    tpa_request_sent: "&aDemande de téléportation envoyée à {player}."
    tpa_request_received: "&e{player} veut se téléporter à vous. Tapez /tpaaccept pour accepter."
    tpahere_request_sent: "&aDemande envoyée à {player} de se téléporter vers vous."
    tpahere_request_received: "&e{player} veut que vous vous téléportiez à lui. Tapez /tpaaccept pour accepter."
    tpa_accepted: "&aVotre demande de téléportation a été acceptée."
    tpa_no_request: "&cVous n'avez aucune demande de téléportation en attente."
    tpa_cooldown: "&cVeuillez patienter {seconds}s avant de refaire une demande."
    tpa_denied_sender: "&cVotre demande de téléportation a été refusée."
    tpa_denied_target: "&eVous avez refusé la demande."
    tpa_expired: "&cLa demande de téléportation a expiré."
  en:
    only_players: "&cThis command is for players only."
    craft_opened: "&aWorkbench opened."
    craft_no_permission: "&cYou don't have permission to use /craft."
    ec_opened: "&aEnderChest opened."
    ec_no_permission: "&cYou don't have permission to use /ec."
    furnace_done: "&aYour items have been smelted."
    furnace_no_permission: "&cYou don't have permission to use /furnace."
    tpa_request_sent: "&aTeleport request sent to {player}."
    tpa_request_received: "&e{player} wants to teleport to you. Type /tpaaccept to accept."
    tpahere_request_sent: "&aTeleport request sent to {player} to teleport to you."
    tpahere_request_received: "&e{player} wants you to teleport to them. Type /tpaaccept to accept."
    tpa_accepted: "&aYour teleport request has been accepted."
    tpa_no_request: "&cYou have no pending teleport request."
    tpa_cooldown: "&cPlease wait {seconds}s before sending another request."
    tpa_denied_sender: "&cYour teleport request was denied."
    tpa_denied_target: "&eYou denied the request."
    tpa_expired: "&cThe teleport request has expired."
