# Language settings: "en_US" ou "fr_FR"
language: "fr_FR"

messages:
  en_US:
    command_no_permission: "§cYou don't have permission!"
    furnace_cooked_hand: "§aCooked §e{0} §aitems in your hand!"
    furnace_no_item: "§cYou must hold an item to cook it!"
    furnace_cooked_all: "§aCooked §e{0} §aitems in your inventory!"

  fr_FR:
    command_no_permission: "§cVous n'avez pas la permission !"
    furnace_cooked_hand: "§aCuisson de §e{0} §aobjets dans votre main !"
    furnace_no_item: "§cVous devez tenir un objet pour le cuire !"
    furnace_cooked_all: "§aCuisson de §e{0} §aobjets dans votre inventaire !"

\1  request_expire_seconds: 60

messages:
  tpa_denied_sender: "&cVotre demande de téléportation a été refusée."
  tpa_denied_target: "&aVous avez refusé la demande."
  tpa_expired: "&cLa demande de téléportation a expiré."
