name: XolbysCommands
main: com.xolby.commands.XolbysCommands
version: 1.0.0
api-version: 1.18
commands:
  tpa:
    description: Demander à se téléporter vers un joueur
    usage: /tpa <joueur>
    permission: xolby.commands.tpa
  tpahere:
    description: Demander à un joueur de se téléporter vers vous
    usage: /tpahere <joueur>
    permission: xolby.commands.tpahere
  tpaaccept:
    description: Accepter la dernière demande de téléportation reçue
    usage: /tpaaccept
    permission: xolby.commands.tpa.accept
  tpadeny:
    description: Refuser la dernière demande de téléportation reçue
    usage: /tpadeny
    permission: xolby.commands.tpa.deny
permissions:
  xolby.commands.tpa:
    description: Utiliser /tpa
    default: true
  xolby.commands.tpahere:
    description: Utiliser /tpahere
    default: true
  xolby.commands.tpa.accept:
    description: Utiliser /tpaaccept
    default: true
  xolby.commands.tpa.deny:
    description: Utiliser /tpadeny
    default: true
