name: XolbysCommands
version: 0.1.0
main: com.xolby.commands.XolbysCommands
api-version: 1.18
commands:
  craft:
    description: Opens a portable crafting table
    usage: /craft
    permission: xolby.commands.craft
  furnace:
    description: Cooks the item in your hand or all items in your inventory
    usage: /furnace [all]
    permission: xolby.commands.furnace
  ec:
    description: Opens your Ender Chest
    usage: /ec
    permission: xolby.commands.ec
permissions:
  xolby.commands.craft:
    default: true
  xolby.commands.furnace:
    default: true
  xolby.commands.ec:
    default: true

tpa:
  description: Demander à se téléporter vers un joueur
  usage: /tpa <joueur>
  permission: xolby.commands.tpa

tpahere:
  description: Demander à un joueur de se téléporter vers vous
  usage: /tpahere <joueur>
  permission: xolby.commands.tpahere

tpaaccept:
  description: Accepter la dernière demande de téléportation reçue
  usage: /tpaaccept
  permission: xolby.commands.tpa.accept

xolby.commands.tpa:
  description: Utiliser /tpa
  default: true

xolby.commands.tpahere:
  description: Utiliser /tpahere
  default: true

xolby.commands.tpa.accept:
  description: Utiliser /tpaaccept
  default: true

tpadeny:
  description: Refuser la demande de téléportation reçue
  usage: /tpadeny
  permission: xolby.commands.tpa.deny

xolby.commands.tpa.deny:
  description: Utiliser /tpadeny
  default: true
