name: XolbysCommands
main: com.xolby.commands.XolbysCommands
version: 1.0.0
api-version: 1.20
commands:
  craft:
    description: Ouvre une table de craft portable
    usage: /craft
    permission: xolby.commands.craft
  furnace:
    description: Cuit instantanément un item ou tout l'inventaire
    usage: /furnace [all]
    permission: xolby.commands.furnace
  ec:
    description: Ouvre votre Ender Chest
    usage: /ec
    permission: xolby.commands.ec
permissions:
  xolby.commands.craft:
    description: Autorise l'utilisation de /craft
    default: op
  xolby.commands.furnace:
    description: Autorise l'utilisation de /furnace et /furnace all
    default: op
  xolby.commands.ec:
    description: Autorise l'utilisation de /ec
    default: op
