name: XolbysCommands
version: 0.1.0
main: com.xolby.commands.XolbysCommands
api-version: 1.18
commands:
  craft:
    description: Opens a portable crafting table
    usage: /craft
    permission: xolby.commands.craft
  furnace:
    description: Cooks the item in your hand or all items in your inventory
    usage: /furnace [all]
    permission: xolby.commands.furnace
  ec:
    description: Opens your Ender Chest
    usage: /ec
    permission: xolby.commands.ec
permissions:
  xolby.commands.craft:
    default: true
  xolby.commands.furnace:
    default: true
  xolby.commands.ec:
    default: true
