name: XolbysCommands
main: com.xolby.commands.XolbysCommands
version: 1.0.0
api-version: 1.18
author: Xolby
commands:
  craft:
    description: Ouvre un établi portable
    usage: /craft
    permission: xcmds.craft
  furnace:
    description: Ouvre un four portable ou smelt all
    usage: /furnace [all]
    permission: xcmds.furnace
  ec:
    description: Ouvre votre EnderChest
    usage: /ec
    permission: xcmds.ec
  sethome:
    description: Définit votre point /home
    usage: /sethome
    permission: xcmds.sethome
  home:
    description: Téléportation à votre /home
    usage: /home
    permission: xcmds.home
  delhome:
    description: Supprime votre /home
    usage: /delhome
    permission: xcmds.delhome
  tpa:
    description: Demander une téléportation vers un joueur
    usage: /tpa <joueur>
    permission: xcmds.tpa
  tpaaccept:
    description: Accepter une demande /tpa
    usage: /tpaaccept
    permission: xcmds.tpa.accept
  tpadeny:
    description: Refuser une demande /tpa
    usage: /tpadeny
    permission: xcmds.tpa.deny
  tpahere:
    description: Demander à un joueur de venir à vous
    usage: /tpahere <joueur>
    permission: xcmds.tpahere
  xcmds:
    description: Liste les commandes du plugin
    usage: /xcmds
    permission: xcmds.help
permissions:
  xcmds.*:
    description: Accès à toutes les commandes
    default: op
    children:
      xcmds.craft: true
      xcmds.furnace: true
      xcmds.ec: true
      xcmds.sethome: true
      xcmds.home: true
      xcmds.delhome: true
      xcmds.tpa: true
      xcmds.tpa.accept: true
      xcmds.tpa.deny: true
      xcmds.tpahere: true
      xcmds.help: true
  xcmds.craft:
    default: true
  xcmds.furnace:
    default: true
  xcmds.ec:
    default: true
  xcmds.sethome:
    default: true
  xcmds.home:
    default: true
  xcmds.delhome:
    default: true
  xcmds.tpa:
    default: true
  xcmds.tpa.accept:
    default: true
  xcmds.tpa.deny:
    default: true
  xcmds.tpahere:
    default: true
  xcmds.help:
    default: true
